language: r
cache: packages

matrix:
  include:
    - os: linux
      dist: precise
      sudo: false
    - os: linux
      dist: trusty
      sudo: required
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode7.2
      brew_packages: cairo
      latex: false
    - os: osx
      osx_image: beta-xcode6.1
      disable_homebrew: true
      latex: false

addons:
  apt:
    packages: libcairo2-dev

after_success:
  - Rscript -e 'covr::codecov()'
